script: make test
language: python
python:
  - "3.7"
install:
  - pip install -r test/requirements.txt
arch:
  - arm64
addons:
  apt:
    packages:
      - gcc-multilib
      - libcap-dev
env:
  - PYTHON_CMD=python3
